name = "rsi-frontend"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
# NEXT_PUBLIC_API_URL = "https://your-backend-url.railway.app/api"
